language: node_js

branches:
  only:
  - master

node_js:
  - 12.16.2

cache:
  - npm
  - yarn

before_install:
  - npm install -g yarn
  - yarn install

script:
  # - yarn lint
  - yarn test
  - yarn build

before_deploy:
  - mv dist synapse-extension
  # 打包压缩
  - zip -q -r synapse-extension.zip synapse-extension
  - rm -rf dist
  # 文件的校验和
  - shasum synapse-extension.zip

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - synapse-extension.zip
  on:
    tags: true
